version: "3.7"

services:
  redis:
    container_name: redis-to-api
    image: redis
    ports:
      - 6379:6379
    restart: always

  app:
    build: .
    container_name: api-redis
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - redis
    depends_on:
      - redis
